### ISSUE TITLE
Cannot install the package 

### ISSUE THREAD

**Issue by yookoala** [upper/cache#2]
I have a package using `upper.io/db`, which some drivers rely on `upper.io/cache`. The latest Travis test worked fine until yesterday. The Travis log shows something like this:

```
...
Fetching https://upper.io/cache?go-get=1
Parsing meta tags from https://upper.io/cache?go-get=1 (status code 200)
import "upper.io/cache": parse https://upper.io/cache?go-get=1: no go-import meta tags
package upper.io/cache: unrecognized import path "upper.io/cache"
...
```

I then checked the upperio website, seems the go-import meta tag is gone. I think that would makes any `go get` against upperio packages fail. Please fix that ASAP. Thanks!

**Comment by krak3n** [comment]
Yes this is currently breaking my installs for `upper.io/db` since it needs `upper.io/cache`

**Comment by VojtechVitek** [comment]
@krak3n I noticed the same thing today. You can workaround it like this:

`cd $GOPATH/src/upper.io && rm -rf cache && git clone git@github.com:upper/cache.git`

**Comment by xiam** [comment]
Thank's for the heads up, I must provide an alternative for when things like this happen, it's fixed now.
